version: "3.7"
services:
    backend:
        build: .
        links:
            - nginx
            - postgres
            - redis
            - mailhog
            - msipay
        environment:
            - ASPNETCORE_ENVIRONMENT
            - MSI_DB_CONNECTION_STRING
            - MSI_SERVER_ADDRESS
            - MSI_REDIS_CONNECTION_STRING=redis
            - MSI_SMTP_HOST=mailhog
            - MSI_PAY_URL=http://msipay:5007/
    msipay:
        build: PaymentApp
        links:
            - nginx
        environment:
            - MSIPAY_DB_CONNECTION_STRING
            - MSIPAY_CALLBACK_URL
            - MSIPAY_SERVER_ADDRESS
    nginx:
        build: ClientApp
        ports:
            - "8080:80"
            - "8081:81"
    postgres:
        image: postgres:alpine
        environment:
            - POSTGRES_DB=msi
            - POSTGRES_USER=msi
            - POSTGRES_PASSWORD=msi
            - PGDATA=/var/lib/postgresql/data/pgdata
        volumes:
            - pgdata:/var/lib/postgresql/data

    redis:
        image: redis:alpine

    mailhog:
        image: mailhog/mailhog:latest
        ports:
            - "8025:8025"
    minio:
        image: minio/minio:latest
        command: ["server", "/data"]
        ports:
            - "9000:9000"
        environment:
            - MINIO_ROOT_USER=msi_s3_root_user
            - MINIO_ROOT_PASSWORD=msi_s3_root_password
            - MINIO_REGION=us-east-1
        volumes:
            - miniodata:/data


volumes:
    pgdata:
    miniodata:
