version: "3.7"
services:
    backend:
        build: .
        links:
            - nginx
            - postgres
        environment:
            - MSI_DB_CONNECTION_STRING
    nginx:
        build: ClientApp
        ports:
            - "8080:80"
    postgres:
        image: postgres:alpine
        environment:
            - POSTGRES_DB=msi
            - POSTGRES_USER=msi
            - POSTGRES_PASSWORD=msi
            - PGDATA=/var/lib/postgresql/data/pgdata
        volumes:
            - pgdata:/var/lib/postgresql/data

volumes:
    pgdata:
