export const SKIP_AUTH_HEADER_NAME = "X-MSI-Skip-Auth";
export const SKIP_AUTH_HEADER_VALUE_AUTH = 1;
export const SKIP_AUTH_HEADER_VALUE_REFRESH = 2;
export const SKIP_AUTH_HEADER_VALUE_AUTH_REFRESH = 3;
export const SKIP_AUTH_HEADER_AUTH = {[SKIP_AUTH_HEADER_NAME]: SKIP_AUTH_HEADER_VALUE_AUTH.toString()};
export const SKIP_AUTH_HEADER_REFRESH = {[SKIP_AUTH_HEADER_NAME]: SKIP_AUTH_HEADER_VALUE_REFRESH.toString()};
export const SKIP_AUTH_HEADER_AUTH_REFRESH = {[SKIP_AUTH_HEADER_NAME]: SKIP_AUTH_HEADER_VALUE_AUTH_REFRESH.toString()};
