name: MSI CI

on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  docker:
    name: Build ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - context: .
            name: backend
          - context: ClientApp
            name: frontend
          - context: PaymentApp
            name: msipay
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          context: ${{ matrix.context }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
